import React from 'react'
import {apiClient as API} from '../../services/apiClient.js'
import RunMetadata from '../RunMetadata.jsx'
import {fmt, FIELDS, defaults} from '../../workbench-utils.js'
import {screenedBands} from '../../decision-utils.mjs'

export default function ModelRuns({a,caseFile,comparison,edit,inputs,perform,presets,priorRun,run,selected,setChallenger,setComparison,setError,setPriorRun,setRun,setSelected,working}) {
  return <><div className="panel"><span className="eyebrow">MODEL INPUTS / HYPOTHETICAL</span><h2>Change an assumption, then run</h2><label>Starting preset <select value={selected} onChange={e=>{if(run) setPriorRun(run);setRun(null);setComparison(null);setChallenger(presets?.presets?.find(p=>p!==e.target.value) || '');setSelected(e.target.value)}}>{presets?.presets?.map(p=><option key={p}>{p}</option>)}</select></label><p>All values below are invented ranges for training. Keep low ≤ mode ≤ high; rates between 0 and 1. Editing changes the run digest.</p><div className="table-wrap" tabIndex="0" role="region" aria-label="Scrollable data table"><table><thead><tr><th>Input</th><th>Low</th><th>Mode</th><th>High</th><th>Unit</th></tr></thead><tbody>{inputs && FIELDS.map(f=><tr key={f}><td>{f.replaceAll('_',' ')}</td>{['low','mode','high'].map(part=><td key={part}><input aria-label={`${f} ${part}`} type="number" step="any" value={inputs[f][part]} onChange={e=>edit(f,part,e.target.value)}/></td>)}<td>{inputs[f].unit}</td></tr>)}</tbody></table></div><button className="primary" disabled={!inputs||working} onClick={()=>perform(async()=>{if (!caseFile.name.trim() || !caseFile.version.trim() || !caseFile.population.trim() || !caseFile.geography.length || caseFile.horizon_months < 1) throw Error('Complete the case name, version, population, geography and horizon first');const value=await API('runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({case:caseFile,scenario_id:selected,scenario_version:'1.0.0',inputs,seed:42,simulation_count:500})});setPriorRun(run || priorRun);screenedBands(value);setRun(value);setComparison(null)})}>Run reproducible model</button></div>{run && <div className="panel"><span className="eyebrow">SAVED LOCAL RUN / {run.run_id}</span><h2>Illustrative screened: {fmt(run.bands.screened.p50)}</h2><p>p10–p90: {fmt(run.bands.screened.p10)}–{fmt(run.bands.screened.p90)}. {run.disclaimer}</p><RunMetadata run={run}/><button className="secondary" onClick={()=>perform(async()=>{const result=await API(`runs/${run.run_id}/replay`);if(result.status!=="REPRODUCED")throw Error("Replay failed");setError("Verified: point and percentile bands reproduced from the stored snapshot")})}>Verify replay</button><button className="secondary" onClick={()=>perform(async()=>setRun(await API('runs/'+run.run_id)))}>Retrieve run by ID</button>{priorRun && priorRun.run_id !== run.run_id && <button className="secondary" onClick={()=>perform(async()=>setComparison(await API(`runs/${priorRun.run_id}/compare/${run.run_id}`)))}>Compare with prior run</button>}{comparison && <div><h3>What changed?</h3><p>Median synthetic screened change: {fmt(comparison.screened_p50_delta)}; real funding decision: {comparison.decision_status}. This is not a causal effect.</p><ul>{comparison.changed_inputs.map(x=><li key={x.variable}>{x.variable}: {JSON.stringify(x.before)} → {JSON.stringify(x.after)}</li>)}</ul></div>}</div>}</>
}
